#!/usr/bin/env bash

# Source all the .sh files in tasks/
for f in ./tasks/*.sh; do source $f; done

set -eu
VERSION=`cat VERSION`
VERSION_DOCKER=$VERSION

if [[ $VERSION_DOCKER == 0.0.* ]] ; then
  VERSION_DOCKER=$VERSION_DOCKER-alpha
fi

# global state array noting which tasks have previously run in this execution
declare -gA already_ran
